nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  ingressAnnotations:
    external-dns.alpha.kubernetes.io/exclude: 'true'
  keyVaults:
    'recipes-sds-kv':
      secrets:
        - name: appInsights-InstrumentationKey
